### ISSUE TITLE
Switch default algorithm for --increm

### ISSUE THREAD

**Issue by jakehlee** [wkiri/DEMUD#20]
Two methods have been implemented for incrementally updating the SVD model: `increm-ross` and `increm-brand`. `--increm` currently defaults to `--svdmethod=increm-ross`. However, comparing the discovery results from these methods and the `full` method (which recomputes the SVD model from scratch at each iteration) shows that the results of `increm-ross` significantly deviate from `full`, whereas `increm-brand` performs similarly to `full`.

Therefore, `--increm` should default to `--svdmethod=increm-brand`, and the message for `--svdmethods` should be updated as such.

**Comment by wkiri** [comment]
Resolved by recent pull request merge.
