### ISSUE TITLE
Add compatibility with Python 3

### ISSUE THREAD

**Issue by wkiri** [wkiri/DEMUD#23]

**Comment by nbertagnolli** [comment]
Are you open to pull requests for this issue?

**Comment by wkiri** [comment]
@nbertagnolli Certainly, thanks for asking!

**Comment by wkiri** [comment]
This issue is complete, and DEMUD now runs with Python 3.  DEMUD has been tested with UCI data sets, float data set with a header, and images.  If anyone encounters snags, feel free to open an issue or contact me.
