### ISSUE TITLE
Demud error messages while installing 

### ISSUE THREAD

**Issue by CindiaMG22** [wkiri/DEMUD#30]

**Comment by jakehlee** [comment]
Hi Cindia, I believe you're running `pip install requirements.txt` instead of `pip install .`, could you see if that fixes your problem? Thanks!

**Comment by CindiaMG22** [comment]
> Hi Cindia, I believe you're running `pip install requirements.txt` instead of `pip install .`, could you see if that fixes your problem? Thanks!

Hi, it did help thank you!
