### ISSUE TITLE
Demud not defined 

### ISSUE THREAD

**Issue by CindiaMG22** [wkiri/DEMUD#31]
Hello, I'm trying to run demud on Spyder on python 3 but it's not defined.

**Comment by jakehlee** [comment]
Please describe the steps you took to install and run `demud`. Note that you should be able to run `demud` directly from the terminal without using an IDE such as Spyder, unless you are trying to import `demud` into a different python script. The [README ](https://github.com/wkiri/DEMUD/blob/master/README.md) has several usage examples.
